spring:
  datasource:
    username: root
    password: 234716
    url: jdbc:mysql://localhost/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

    #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #数据监控
    filters: stat

  redis:
    port: 6379
    host: 192.168.137.118
mybatis:
 # config-location: classpath:/mybatis/mybatis-config.xml #指定主配置文件
 # mapper-locations: classpath:/mybatis/mapper/*.xml # 指定xml映射文件路径
 type-aliases-package: com.atguigu.domain # 指定mybatis别名包
logging:
  level:
    com.atguihu: debug #配置日志

  jpa:
    #指定数据库提供商
    database: mysql
    #打印SQL
    show-sql: true
    #是jpa层面对数据表生成策略的控制
    generate-ddl: true
    hibernate:
      #是jpa实现hibernate层面上对数据表生成策略的控制
      ddl-auto: update
      #指定命名策略
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    main:
      allow-bean-definition-overriding: true